package by.etc.shop.controller.command;

public enum CommandName {
    SIGNIN,
    REGISTRATION,
    SIGNOUT,

    CHANGELANGUAGE,

    ADDPRODUCT,
    DELETEPRODUCT,
    CHANGEPRODUCT,
    FINDPRODUCTBYID,

    ADDSTOCK,
    CHANGESTOCK,
    DELETESTOCK,

    ADDTOBASKET,
    CHANGEQUANTITY,
    DELETEFROMBASKET,
    BASKETPRODUCT;
}
